FROM python:alpine
WORKDIR /src
ENV TIKA_SERVER_JAR="file:///src/tika-server-1.24.jar"
CMD ["python", "main.py"]

# Add jar separately since it's unlikely to change
# and it's rather large
ADD tika-server-1.24.jar /src

RUN apk add \
    gcc \
    libxml2 \
    libxml2-dev \
    musl-dev \
    libxslt \
    libxslt-dev \
    openjdk8-jre \
    poppler-utils

ADD requirements.txt /src
RUN pip install -r requirements.txt

ADD . /src